apiVersion: skaffold/v2beta1
kind: Config
profiles:
- name: test-cronjob
  deploy:
    helm:
      flags:
        install: ['--atomic']
        upgrade: ['--atomic']
      releases:
      - name: cronjob
        namespace: default
        chartPath: ./charts/basic
        #chartPath: test-cronjob/basic
        #remote: true
        wait: true
        valuesFiles:
          - values.yaml
